name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # (Ton projet est dans le dossier lab5)
      - name: Install dependencies
        run: npm ci
        working-directory: lab5

      - name: Build (if present)
        run: npm run build --if-present
        working-directory: lab5

      - name: Test
        run: npm test
        working-directory: lab5
