name: Node.js CI (with Redis)

on:
  push:
    branches: ["maeli", "master"]
  pull_request:
    branches: ["maeli", "master"]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Detect app directory
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "dir=." >> "$GITHUB_OUTPUT"
          elif [ -f lab5/package.json ]; then
            echo "dir=lab5" >> "$GITHUB_OUTPUT"
          else
            echo "No package.json found at '.' or 'lab5'." >&2
            exit 1
          fi

      - name: Install deps
        run: |
          cd "${{ steps.detect.outputs.dir }}"
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (if present)
        run: |
          cd "${{ steps.detect.outputs.dir }}"
          npm run build --if-present

      - name: Test (with Redis env)
        env:
          REDIS_URL: redis://localhost:6379
          REDIS_HOST: localhost
          REDIS_PORT: "6379"
        run: |
          cd "${{ steps.detect.outputs.dir }}"
          if npm run | grep -qE '^\s*test'; then
            npm test
          else
            echo "No tests"
          fi
